### ISSUE TITLE
Failed to set client characteristic read for ...

### ISSUE THREAD

**Issue by Allanon29** [nativescript-community/ble#103]
Hi Guys,

Trying to read data from my Max Buzz device but I get this error when I try to read it:
JS: 'Periperhal connected with UUID: E3:8A:D2:68:17:6A'
JS: 'read error: Failed to set client characteristic read for 00002a01-0000-1000-8000-00805f9b34fb'

Any idea why this happens?

**Comment by Geeta-Singh** [comment]
I'm also getting the same issue.
My code
bluetooth.connect({
  UUID: uuid,
  onConnected: (peripheral) => {

    peripheral.services.forEach((service) => {
      console.log("service found: " + JSON.stringify(service));
      this.deviceServiceData = service;
    });
    setTimeout(() => {
      this.readDataFromDevice(this.deviceServiceData, uuid);
      this.notify(this.deviceServiceData, uuid);
    }, 1000);

  },
  onDisconnected: function (peripheral) {
    console.log("Periperhal disconnected with UUID: " + peripheral.UUID);
  }
});
}

notify(service, uuid) {

  bluetooth.startNotifying({
    peripheralUUID: uuid,
    serviceUUID: service.UUID,
    characteristicUUID: service.characteristics[0].UUID,
    onNotify: function (result) {
    console.log("read: " + JSON.stringify(result));
   }
  }).then(function () {
    console.log("subscribed for notifications");
  }, function (err) {
    console.log("notify error error: " + err);
 });
 }

 readDataFromDevice(service, uuid) {

 bluetooth.read({
  peripheralUUID: uuid,
  serviceUUID: service.UUID,
  characteristicUUID: service.characteristics[0].UUID,

 }).then((result) => {
  var data = new Uint8Array(result.value);
  console.log(data);
 }, function (err) {
  console.log("read error: " + err);
 });
}
