### ISSUE TITLE
Using as Peripheral

### ISSUE THREAD

**Issue by bvkdevelopment** [nativescript-community/ble#104]
Hi,

Is it posible to make virtual peripheral with this library. Actually ı need to use phone as a peripheral not central.

Thanks in advanced

**Comment by bradmartin** [comment]
It is possible but some things are still needed on this plugin I believe. I have a local fork in a project that is doing this, we planned to push things back to here as a PR but it's very involved with bluetooth code so it's not a simple PR to polish up 😄 - but you can definitely use this as a base.
