### ISSUE TITLE
Connecting two instances of Nativescript application

### ISSUE THREAD

**Issue by milejko** [nativescript-community/ble#117]
Let's say, we have two instances of the same Nativescript app - can we just send data from one to another? This is a common case in some sort of apps (like games for example). I would like to send a few bytes between 2 devices is it possible with this plugin?

**Comment by EddyVerbruggen** [comment]
AFAIK you can not use this plugin to act as a peripheral.

**Comment by milejko** [comment]
Pity, but thanks for the answer. Regards
