### ISSUE TITLE
Feature Request: Handle Read Queueing Internally

### ISSUE THREAD

**Issue by drewcovi** [nativescript-community/ble#127]
At present, sequential read requests will get dropped as they pile up. Multiple read requests are super helpful when pulling down all information in a service (all device information for instance).

The current solution is to simply `await` the read request as it returns a promise. Even if there's no solution proposed, it would help to document these nuances.

**Comment by farfromrefug** [comment]
@drewcovi what platform are you talking about?

**Comment by drewcovi** [comment]
@farfromrefug testing on iOS for now

**Comment by farfromrefug** [comment]
@drewcovi should be working. Did not have time to test but it should work now.

**Comment by drewcovi** [comment]
@farfromrefug you're on fire.
