### ISSUE TITLE
Send pairing key (PIN) to Bluetooth device (glucose monitor)

### ISSUE THREAD

**Issue by JeffersonLPLima** [nativescript-community/ble#129]
I am trying to pair my glucose monitor, but it is requesting a pairing key (6 digit PIN).  I would like to pair so that next time the monitor already recognizes my smartphone.
  **So, how can I send the PIN through the `bluetooth.connect` method?**
I can already read infromations from monitor even without entering the PIN, but the monitor does not pair.

**Comment by farfromrefug** [comment]
This is out of the scope of that module. Please read the specs of your device. Everything should be written on how to connect to it. Not even sure this is a BLE device.

**Comment by Tyler-V** [comment]
@farfromrefug some devices require pairing where you have to enter a PIN and will not let you interact with the device services until you have done so.

Manually pairing and entering the pin then allows you to connect to the device via UUID.

Many android apps allow device pairing within the application where you enter the PIN and are able to pair without leaving the app.

This seems integral to a bluetooth library and in scope to this module. Can we reevaluate this issue?

**Comment by farfromrefug** [comment]
@Tyler-V  seems to me like you are talking about bluetooth 2.0 devices. this plugin is for ble  devices .

**Comment by Tyler-V** [comment]
@farfromrefug bluetooth [LE 4.0 and 4.1 use Secure Simple Pairing (SSP)](https://security.stackexchange.com/questions/116027/difference-between-secure-simple-pairing-and-secure-connections-in-bluetooth) which is different from legacy pairing. It uses Passkey Entry, which requires you to enter a 6-digit numeric code to prevent MITM attacks.

The device I am using is a Contour Next One bluetooth glucose meter which follows the 4.0 specification.

**Comment by farfromrefug** [comment]
@Tyler-V did not know about SSP on BLE! never used a device which used it.
Maybe you could make a PR?
