### ISSUE TITLE
Error on android when calling startScanning()

### ISSUE THREAD

**Issue by JoshuaMcCoy** [nativescript-community/ble#143]
my code was working until I updated nativescript, now when I call startScanning() on android, I get the following error:
```
[moto x4]: ERROR TypeError: Cannot read property 'scan' of undefined

[moto x4]: Error in Bluetooth.startScanning: TypeError: Cannot read property 'ContextCompat' of undefined

[moto x4]: error while scanning: TypeError: Cannot read property 'ContextCompat' of undefined
```

it even happens when the code is exactly as recommended in the example:

```
bluetooth.startScanning({

  serviceUUIDs: [],

  seconds: 4,

  onDiscovered: function (peripheral) {

  	console.log("Periperhal found with UUID: " + peripheral.UUID);

  },

  skipPermissionCheck: false,

}).then(function() {

  console.log("scanning complete");

}, function (err) {

  console.log("error while scanning: " + err);

});
```

**Comment by Exxili** [comment]
Having Same issue - ContextCompat Error as well

**Comment by EddyVerbruggen** [comment]
That’s because N6 uses AndroidX. I’ve got a local fix but not entirely sure about what to release at this point: master or the v2 branch. Should be more clear soon..

**Comment by JoshuaMcCoy** [comment]
@EddyVerbruggen 
Thanks for creating this useful package! Is the local fix you have in place straight forward enough for you to point me at the solution? Dont worry about it if it will take you away from working on your commit.

**Comment by toams69** [comment]
Having Same issue - ContextCompat Error as well

`TypeError: Cannot read property 'ContextCompat' of undefined
JS:     at Object.push.../node_modules/nativescript-bluetooth/bluetooth.js.Bluetooth._coarseLocationPermissionGranted file:///node_modules/nativescript-bluetooth/bluetooth.js:18:35
JS:     at file:///node_modules/nativescript-bluetooth/bluetooth.js:517:57
JS:     at new Promise (<anonymous>)
JS:     at Object.push.../node_modules/nativescript-bluetooth/bluetooth.js.Bluetooth.startScanning file:///node_modules/nativescript-bluetooth/bluetooth.js:444:9

**Comment by Ravaniss** [comment]
same here

**Comment by JoshuaMcCoy** [comment]
upgrading to nativescriptbluetooth@beta can resolve this issue.  there are some differences in the way various methods work in the beta version, but they are minor and i was able to use intelesense to figure out the changes.

to install:
`npm install nativescript-bluetooth@beta`

to use, I declare it like this:
`import { Bluetooth } from 'nativescript-bluetooth';
const bluetooth = new Bluetooth();`

**Comment by nuochong** [comment]
same here

**Comment by schnapzz** [comment]
Had the same issue, fixed it by changing the following in the built node_modules/nativescript-bluetooth/bluetooth.android.js, line no. ~18

`android.support.v4.content.ContextCompat.checkSelfPermission(application.android.foregroundActivity, android.Manifest.permission.ACCESS_COARSE_LOCATION);
`
to 
`androidx.core.content.ContextCompat.checkSelfPermission(application.android.foregroundActivity, android.Manifest.permission.ACCESS_COARSE_LOCATION);`

This is following the new class mappings to androidx from the Android Dev team [here](https://developer.android.com/jetpack/androidx/migrate/class-mappings). This is by no means a solid solution but for my project it is sufficient untill a patch to the plugin is live.

**Comment by StephaniesHusband** [comment]
When i use the @beta version Android starts working but the iOS version does not work anymore. Anyone else seeing this?

**Comment by methompson** [comment]
I know this hasn't been resolved yet, but I took the suggestion of @schnapzz and placed the following in my NS-Vue app to bridge compatibility. I check that android.support.v4 exists in the global object, then copy a reference to android.core.content.ContextCompat into android.support.v4.content.ContextCompat.

I don't believe this is a particularly good solution, but it's workable without actually modifying any modules.


```
// in app.js
import { isAndroid } from "tns-core-modules/platform";

if (isAndroid) {
  if ( android
    && android.support
    && android.support.v4
  ) {
    android.support.v4.content = {
      ContextCompat: androidx.core.content.ContextCompat,
    };
  }
}
```
