### ISSUE TITLE
iOS - check to see if specific device is already connected

### ISSUE THREAD

**Issue by JoshuaMcCoy** [nativescript-community/ble#144]
my device automatically connects to the phone when in range, and stops advertising, which prevents it from being seen during scan(). but I know this object's information, is there a way for me to connect to the device?

**Comment by JoshuaBThompson** [comment]
I have the same request, this would be VERY useful!

**Comment by farfromrefug** [comment]
Look for the "isConnected" method. Look at the typings to se e the options

**Comment by JoshuaBThompson** [comment]
> Look for the "isConnected" method. Look at the typings to se e the options

thanks! sorry forgot to reply
