### ISSUE TITLE
Setting MTU

### ISSUE THREAD

**Issue by detonimarco** [nativescript-community/ble#149]
Hi,
To download data from BLE device I need to set MTU to find the best communications speed.
Is there a way to set MTU on android using, for instance, requestMtu?
I'm using version 2.0.0-beta.23

Thanks

**Comment by farfromrefug** [comment]
@detonimarco you have a ```requestMtu``` method on ```Bluetooth```. For now it only works on Android

**Comment by detonimarco** [comment]
@farfromrefug thx I'm testing.
 I didn't realize I can use the other methods.

**Comment by vidicj** [comment]
@farfromrefug are there any plans to implement this on iOS as well? I seem to be having issues where the MTU on the mobile is 185, but BT device thinks it is 244...

**Comment by farfromrefug** [comment]
@vidicj it is already supported and working on iOS
