### ISSUE TITLE
Bluetooth plugin not working on iOS device

### ISSUE THREAD

**Issue by prabudevarrajan** [nativescript-community/ble#169]
I cloned the project and tried to run the demo app. On Android, the demo app works fine without any issue. But same app on my iOS device doesn't work.

When I clicked on "Is Bluetooth Enabled?", is says "Bluetooth is DISABLED". But, I checked the phone settings and bluetooth service is enabled. 

iOS device information
iPhone 6s 
iOS version 13.2.3

**Comment by manojdcoder** [comment]
@prabudevarrajan Do you still have the issue, can you share a sample project?

**Comment by luca-mayven** [comment]
+1

**Comment by luca-mayven** [comment]
I have the same issue on an iPhone 11 Pro iOS 13.2.3

**Comment by toams69** [comment]
Same issue here.
Was working fine before the update of IOS.

**Comment by toams69** [comment]
Fixed on my side by adding the key NSBluetoothAlwaysUsageDescription in the info.plist

https://developer.apple.com/documentation/bundleresources/information_property_list/nsbluetoothalwaysusagedescription

**Comment by manojdcoder** [comment]
`NSBluetoothAlwaysUsageDescription` was recently introduced in iOS 13. Without that your app could crash.

I just ran a test on iOS 13.2.3, it worked just fine.

**Comment by luca-mayven** [comment]
Thanks a lot @toams69 and @manojdcoder !

It works fine now that I added the key as well.

Now it seems to be scanning correctly but the list looks empty. 

In any case the original issue is solved.

Thanks

Luca

**Comment by Joebh** [comment]
Using 3.0.0-beta.10 I'm not able to see any bluetooth devices while scanning on ios 12 iphone 5s, anyone able to get it working with that version?

**Comment by manojdcoder** [comment]
@Joebh Were you able to test it on any other devices, perhaps one with iOS 13?

**Comment by farfromrefug** [comment]
I am using the latest beta in production on iOS and Android. It is working fine everywhere. Check you logs you might be missing permissions

**Comment by Joebh** [comment]
@manojdcoder verified it's working ios13 ty, haven't found the issue yet for 12.

**Comment by manojdcoder** [comment]
I have to setup iOS 12, I will update when I do so.
