### ISSUE TITLE
Module not found v3.0.11

### ISSUE THREAD

**Issue by gurvan-guss** [nativescript-community/ble#200]
Hello,

It seems there is a problem with the latest version, I updated the plugin from v3.0.9 to v3.0.11 (even if there are no changes) but I got the following error `Module not found: Error: Can't resolve '@nativescript-community/ble'`

Downgrading to v3.0.9 or below solve the problem.

**Comment by farfromrefug** [comment]
@gurvan-guss I see the issue thanks  will fix

**Comment by farfromrefug** [comment]
@gurvan-guss sorry for not getting back to you. You saw I made a release I guess ;)

**Comment by gurvan-guss** [comment]
@farfromrefug Yup :)
