### ISSUE TITLE
advertismentData is always empty in each onDescovery call of startScanning api

### ISSUE THREAD

**Issue by amidnikmal** [nativescript-community/ble#212]
Hello. Why in each onDescovery callback all peritherals has empty advertismentData ?

If i scan devices with nrfConnect app i see all devices and also all advertise data. How to get same data with your plugin ?

```
{
   "type": "scanResult",
   "UUID": "test",
   "name": "test",
   "RSSI": -49,
   "localName": null,
   "state": "disconnected",
   "manufacturerId": 00,
   "advertismentData": {
     "scanRecord": {}
 }
```

If there are way to get raw advertising package ?

**Comment by farfromrefug** [comment]
it is because it is an object with getters. logging it like you do reports it as empty when it is not

**Comment by amidnikmal** [comment]
Thank you
