### ISSUE TITLE
Get native android BluetoothDevice instance

### ISSUE THREAD

**Issue by matthew798** [nativescript-community/ble#217]
I am using a native android library (written in Java) and in order to use it, I need to pass it an instance of `BluetoothDevice`. Is there a way to get the native representation of the device on Android?

**Comment by farfromrefug** [comment]
@matthew798 i just added what you need:
* `nativeDevice` in scan / connect events/callbacks
* `getDevice` method to get native device using UUID

**Comment by matthew798** [comment]
Thanks!!!
