### ISSUE TITLE
Ios give me long uuid while android give me macaddress style

### ISSUE THREAD

**Issue by Atomico001** [nativescript-community/ble#218]
Hello, i have a problem with ios and android data.

in ios i have this:
{
"UUID" : 83621c1a-7cfd-3d3b-b223-46fecbc9ec8"
...
}
while on android i have:
{
"UUID": DC:0D:30:04:2F:C3
...
}

Why?

**Comment by farfromrefug** [comment]
@Atomico001 you need to look at native API documentations for device ids. This is the normal behavior.

**Comment by Atomico001** [comment]
Thanks for answer, but i download an ios app to scan beacons and i can see the mac address there.
Another thing is that that uuid 83621c1a-7cfd-3d3b-b223-46fecbc9ec8 is nowhere in my beacon config. Is it a fake uuid?

**Comment by farfromrefug** [comment]
@Atomico001 that is what i am talking about this is not the mac address. this is a unique id given by the system. You should read the native docs
