### ISSUE TITLE
bluetooth.disconnect resolving does not indicate complete disconnection

### ISSUE THREAD

**Issue by msn444** [nativescript-community/ble#223]
If you immediately try to reconnect to a device after the `disconnect` promise resolves, the subsequent call to `connect` will not succeed. You must wait for the `onDisconnected` callback before attempting to connect again. On my device (Android Pixel 3) `onDisconnected` is always called immediately after `disconnect` resolves.

If this is by design, the documentation should be updated to reflect this -- I assumed that simply awaiting `disconnect` would be sufficient.

**Comment by farfromrefug** [comment]
@msn444 BLE disconnection are not sync indeed.PRs are welcome if you want to. update the doc.
