### ISSUE TITLE
Discover and connect to beacons

### ISSUE THREAD

**Issue by ju4nj3** [nativescript-community/ble#232]
Please, could someone give some light to read or discover the UUIDs beacon slots, minor or major values?
Dumped entire peripheral object onConnected event, shows another UUID different to the configured on the beacon.
Also, if I setup two slots on the same beacon with same UUID, same major, and different minor, can't connect to the beacon.

![photo_2021-07-24_13-47-29](https://user-images.githubusercontent.com/13917228/126867709-2a8ca8f5-0d76-4539-95df-07f7e50978d6.png)

Peripheral connected with UUID: ED:21:03:98:66:E4

{
    "UUID": "ED:21:03:98:66:E4",
    "name": "iBKS105",
    "state": "connected",
    "services": [
        {
            "UUID": "1800",
            "characteristics": [
                {
                    "serviceUUID": "1800",
                    "UUID": "2a00",
                    "name": "2a00",
                    "properties": {
                        "read": true,
                        "write": true,
                        "writeWithoutResponse": false,
                        "notify": false,
                        "indicate": false,
                        "broadcast": false,
                        "authenticatedSignedWrites": false,
                        "extendedProperties": false
                    },
                    "descriptors": [],
                    "permissions": null
                },
                {
                    "serviceUUID": "1800",
                    "UUID": "2a01",
                    "name": "2a01",
                    "properties": {
                        "read": true,
                        "write": false,
                        "writeWithoutResponse": false,
                        "notify": false,
                        "indicate": false,
                        "broadcast": false,
                        "authenticatedSignedWrites": false,
                        "extendedProperties": false
                    },
                    "descriptors": [],
                    "permissions": null
                },
                {
                    "serviceUUID": "1800",
                    "UUID": "2a04",
                    "name": "2a04",
                    "properties": {
                        "read": true,
                        "write": false,
                        "writeWithoutResponse": false,
                        "notify": false,
                        "indicate": false,
                        "broadcast": false,
                        "authenticatedSignedWrites": false,
                        "extendedProperties": false
                    },
                    "descriptors": [],
                    "permissions": null
                }
            ]
        },
        {
            "UUID": "1801",
            "characteristics": [
                {
                    "serviceUUID": "1801",
                    "UUID": "2a05",
                    "name": "2a05",
                    "properties": {
                        "read": false,
                        "write": false,
                        "writeWithoutResponse": false,
                        "notify": false,
                        "indicate": true,
                        "broadcast": false,
                        "authenticatedSignedWrites": false,
                        "extendedProperties": false
                    },
                    "descriptors": [
                        {
                            "UUID": "2902",
                            "value": null,
                            "permissions": null
                        }
                    ],
                    "permissions": null
                }
            ]
        },
        {
            "UUID": "180a",
            "characteristics": [
                {
                    "serviceUUID": "180a",
                    "UUID": "2a29",
                    "name": "2a29",
                    "properties": {
                        "read": true,
                        "write": false,
                        "writeWithoutResponse": false,
                        "notify": false,
                        "indicate": false,
                        "broadcast": false,
                        "authenticatedSignedWrites": false,
                        "extendedProperties": false
                    },
                    "descriptors": [],
                    "permissions": null
                },
                {
                    "serviceUUID": "180a",
                    "UUID": "2a25",
                    "name": "2a25",
                    "properties": {
                        "read": true,
                        "write": false,
                        "writeWithoutResponse": false,
                        "notify": false,
                        "indicate": false,
                        "broadcast": false,
                        "authenticatedSignedWrites": false,
                        "extendedProperties": false
                    },
                    "descriptors": [],
                    "permissions": null
                },
                {
                    "serviceUUID": "180a",
                    "UUID": "2a27",
                    "name": "2a27",
                    "properties": {
                        "read": true,
                        "write": false,
                        "writeWithoutResponse": false,
                        "notify": false,
                        "indicate": false,
                        "broadcast": false,
                        "authenticatedSignedWrites": false,
                        "extendedProperties": false
                    },
                    "descriptors": [],
                    "permissions": null
                },
                {
                    "serviceUUID": "180a",
                    "UUID": "2a28",
                    "name": "2a28",
                    "properties": {
                        "read": true,
                        "write": false,
                        "writeWithoutResponse": false,
                        "notify": false,
                        "indicate": false,
                        "broadcast": false,
                        "authenticatedSignedWrites": false,
                        "extendedProperties": false
                    },
                    "descriptors": [],
                    "permissions": null
                }
            ]
        },
        {
            "UUID": "a3c87500-8ed3-4bdf-8a39-a01bebede295",
            "characteristics": [
                {
                    "serviceUUID": "a3c87500-8ed3-4bdf-8a39-a01bebede295",
                    "UUID": "a3c87501-8ed3-4bdf-8a39-a01bebede295",
                    "name": "a3c87501-8ed3-4bdf-8a39-a01bebede295",
                    "properties": {
                        "read": tr
ue,
                        "write": false,
                        "writeWithoutResponse": false,
                        "notify": false,
                        "indicate": false,
                        "broadcast": false,
                        "authenticatedSignedWrites": false,
                        "extendedProperties": false
                    },
                    "descriptors": [],
                    "permissions": null
                },
                {
                    "serviceUUID": "a3c87500-8ed3-4bdf-8a39-a01bebede295",
                    "UUID": "a3c87502-8ed3-4bdf-8a39-a01bebede295",
                    "name": "a3c87502-8ed3-4bdf-8a39-a01bebede295",
                    "properties": {
                        "read": true,
                        "write": true,
                        "writeWithoutResponse": false,
                        "notify": false,
                        "indicate": false,
                        "broadcast": false,
                        "authenticatedSignedWrites": false,
                        "extendedProperties": false
                    },
                    "descriptors": [],
                    "permissions": null
                },
                {
                    "serviceUUID": "a3c87500-8ed3-4bdf-8a39-a01bebede295",
                    "UUID": "a3c87503-8ed3-4bdf-8a39-a01bebede295",
                    "name": "a3c87503-8ed3-4bdf-8a39-a01bebede295",
                    "properties": {
                        "read": true,
                        "write": true,
                        "writeWithoutResponse": false,
                        "notify": false,
                        "indicate": false,
                        "broadcast": false,
                        "authenticatedSignedWrites": fals
e,
                        "extendedProperties": false
                    },
                    "descriptors": [],
                    "permissions": null
                },
                {
                    "serviceUUID": "a3c87500-8ed3-4bdf-8a39-a01bebede295",
                    "UUID": "a3c87504-8ed3-4bdf-8a39-a01bebede295",
                    "name": "a3c87504-8ed3-4bdf-8a39-a01bebede295",
                    "properties": {
                        "read": true,
                        "write": true,
                        "writeWithoutResponse": false,
                        "notify": false,
                        "indicate": false,
                        "broadcast": false,
                        "authenticatedSignedWrites": false,
                        "extendedProperties": false
                    },
                    "descriptors": [],
                    "perm
issions": null
                },
                {
                    "serviceUUID": "a3c87500-8ed3-4bdf-8a39-a01bebede295",
                    "UUID": "a3c87505-8ed3-4bdf-8a39-a01bebede295",
                    "name": "a3c87505-8ed3-4bdf-8a39-a01bebede295",
                    "properties": {
                        "read": true,
                        "write": true,
                        "writeWithoutResponse": false,
                        "notify": false,
                        "indicate": false,
                        "broadcast": false,
                        "authenticatedSignedWrites": false,
                        "extendedProperties": false
                    },
                    "descriptors": [],
                    "permissions": null
                },
                {
                    "serviceUUID": "a3c87500-8ed3-4bdf-8a39-a01bebede295",
                    "UUID": "a3c87506-8ed3-4bdf-8a39-a01bebede295",
                    "name": "a3c87506-8ed3-4bdf-8a39-a01bebede295",
                    "properties": {
                        "read": true,
                        "write": true,
                        "writeWithoutResponse": false,
                        "notify": false,
                        "indicate": false,
                        "broadcast": false,
                        "authenticatedSignedWrites": false,
                        "extendedProperties": false
                    },
                    "descriptors": [],
                    "permissions": null
                },
                {
                    "serviceUUID": "a3c87500-8ed3-4bdf-8a39-a01bebede295",
                    "UUID": "a3c87507-8ed3-4bdf-8a39-a01bebede295",
                    "name": "a3c87507-8ed3-4bdf-8a39-a01bebede295",
                    "
properties": {
                        "read": true,
                    "write": true,
                    "writeWithoutResponse": false,
                    "notify": false,
                    "indicate": false,
                    "broadcast": false,
                    "authenticatedSignedWrites": false,
                    "extendedProperties": false
                },
                "descriptors": [],
                "permissions": null
            },
            {
                "serviceUUID": "a3c87500-8ed3-4bdf-8a39-a01bebede295",
                "UUID": "a3c87508-8ed3-4bdf-8a39-a01bebede295",
                "name": "a3c87508-8ed3-4bdf-8a39-a01bebede295",
                "properties": {
                    "read": true,
                    "write": false,
                    "writeWithoutResponse": f
alse,
                    "notify": false,
                    "indicate": false,
                    "broadcast": false,
                    "authenticatedSignedWrites": false,
                    "extendedProperties": false
                },
                "descriptors": [],
                "permissions": null
            },
            {
                "serviceUUID": "a3c87500-8ed3-4bdf-8a39-a01bebede295",
                "UUID": "a3c87509-8ed3-4bdf-8a39-a01bebede295",
                "name": "a3c87509-8ed3-4bdf-8a39-a01bebede295",
                "properties": {
                    "read": true,
                    "write": false,
                    "writeWithoutResponse": false,
                    "notify": false,
                    "indicate": false,
                    "broadcast": false,
                    "authenticatedSignedWrites": false,
                    "extendedProperties": false
                },
                "descriptors": [],
                "permissions": null
            },
            {
                "serviceUUID": "a3c87500-8ed3-4bdf-8a39-a01bebede295",
                "UUID": "a3c8750a-8ed3-4bdf-8a39-a01bebede295",
                "name": "a3c8750a-8ed3-4bdf-8a39-a01bebede295",
                "properties": {
                    "read": true,
                    "write": true,
                    "writeWithoutResponse": false,
                    "notify": false,
                    "indicate": false,
                    "broadcast": false,
                    "authenticatedSignedWrites": false,
                    "extendedProperties": false
                },
                "descriptors": [],
                "permissions": null
            },
            {
                "serviceUUID": "a3c87500-8ed3-4bdf-8a39-a01bebede295",
                "UUID": "a3c8750b-8ed3-4bdf-8a39-a01bebede295",
                "name": "a3c8750b-8ed3-4bdf-8a39-a01bebede295",
                "properties": {
                    "read": false,
                    "write": true,
                    "writeWithoutResponse": false,
                    "notify": false,
                    "indicate": false,
                    "broadcast": false,
                    "authenticatedSignedWrites": false,
                    "extendedProperties": false
                },
                "descriptors": [],
                "permissions": null
            },
            {
                "serviceUUID": "a3c
87500-8ed3-4bdf-8a39-a01bebede295",
                    "UUID": "a3c8750c-8ed3-4bdf-8a39-a01bebede295",
                "name": "a3c8750c-8ed3-4bdf-8a39-a01bebede295",
                "properties": {
                    "read": true,
                    "write": true,
                    "writeWithoutResponse": false,
                    "notify": false,
                    "indicate": false,
                    "broadcast": false,
                    "authenticatedSignedWrites": false,
                    "extendedProperties": false
                },
                "descriptors": [],
                "permissions": null
            }
        ]
    },
    {
        "UUID": "fa00",
        "characteristics": [
            {
                "serviceUUID": "fa00",
                "UUID": "fa01",
                "name": "fa01",
                "properties": {
                    "read": true,
                    "write": true,
                    "writeWithoutResponse": false,
                    "notify": false,
                    "indicate": false,
                    "broadcast": false,
                    "authenticatedSignedWrites": false,
                    "extendedProperties": false
                },
                "descriptors": [],
                "permissions": null
            },
            {
                "serviceUUID": "fa00",
                "UUID": "fa02",
                "name": "fa02",
                "properties": {
                    "read": true,
                    "write": true,
                    "writeWithoutResponse": false,
                    "notify": false,
                    "indicate": false,
                    "broadcast": false,
                    "authenticatedSignedWrites": false,
                    "extendedProperties": false
                },
                "descriptors": [],
                "permissions": null
            },
            {
                "serviceUUID": "fa00",
                "UUID": "fa03",
                "name": "fa03",
                "properties": {
                    "read": true,
                    "write": true,
                    "writeWithoutResponse": false,
                    "notify": false,
                    "indicate": false,
                    "broadcast": false,
                    "authenticatedSignedWrites": false,
                    "extendedProperties": false
                },
                "descriptors": [],
                "permissions": null
            },
            {
                "serviceUUID": "fa00",
                "UUID": "fa04",
                "name": "fa04",
                "properties": {
                    "read": true,
                    "write": true,
                    "writeWithoutResponse": false,
                    "notify": false,
                    "indicate": false,
                    "broadcast": false,
                    "authenticatedSignedWrites": false,
                    "extendedProperties": false
                },
                "descriptors": [],
                "permissions": null
            },
            {
                "serviceUUID": "fa00",
                "UUID": "fa05",
                "name": "fa05",
                    "pr
operties": {
                        "read": true,
                "write": true,
                "writeWithoutResponse": false,
                "notify": false,
                "indicate": false,
                "broadcast": false,
                "authenticatedSignedWrites": false,
                "extendedProperties": false
            },
            "descriptors": [],
            "permissions": null
        },
        {
            "serviceUUID": "fa00",
            "UUID": "fa06",
            "name": "fa06",
            "properties": {
                "read": true,
                "write": true,
                "writeWithoutResponse": false,
                "notify": false,
                "indicate": false,
                "broadcast": false,
                "authenticatedSignedWrites": false,
                "extendedProperties": false
            },
            "descriptors": [],
            "permissions": null
        }
    ]
},
{
    "UUID": "ff00",
    "characteristics": [
        {
            "serviceUUID": "ff00",
            "UUID": "ff01",
            "name": "ff01",
            "properties": {
                "read": true,
                "write": true,
                "writeWithoutResponse": false,
                "notify": false,
                "indicate": false,
                "broadcast": false,
                "authenticatedSignedWrites": false,
                "extendedProperties": fa
lse
            },
            "descriptors": [],
            "permissions": null
        },
        {
            "serviceUUID": "ff00",
            "UUID": "ff02",
            "name": "ff02",
            "properties": {
                "read": true,
                "write": false,
                "writeWithoutResponse": false,
                "notify": false,
                "indicate": false,
                "broadcast": false,
                "authenticatedSignedWrites": false,
                "extendedProperties": false
            },
            "descriptors": [],
            "permissions": null
        },
        {
            "serviceUUID": "ff00",
            "UUID": "ff03",
            "name": "ff03",
            "properties": {
                "read": true,
                "write": true,
                "writeWithoutResponse": false,
                "notify": false,
                "indicate": false,
                "broadcast": false,
                "authenticatedSignedWrites": false,
                "extendedProperties": false
            },
            "descriptors": [],
            "permissions": null
        },
        {
            "serviceUUID": "ff00",
            "UUID": "ff04",
            "name": "ff04",
            "properties": {
                "read": true,
                "write": true,
                "writeWithoutResponse": false,
                "notify": false,
                "indicate": false,
                "broadcast": false,
                "authenticatedSignedWrites": false,
                "extendedProperties": false
            },
            "descriptors": [],
            "permissions": null
        },
        {
            "serviceUUID": "ff00",
            "UUID": "ff05",
            "name": "ff05",
            "properties": {
                "read": false,
                "write": true,
                "writeWithoutResponse": false,
                "notify": false,
                "indicate": false,
                "broadcast": false,
                "authenticatedSignedWrites": false,
                "extendedProperties": false
            },
                    "de
scriptors": [],
                    "permissions": null
        },
        {
            "serviceUUID": "ff00",
            "UUID": "ff06",
            "name": "ff06",
            "properties": {
                "read": true,
                "write": true,
                "writeWithoutResponse": false,
                "notify": false,
                "indicate": false,
                "broadcast": false,
                "authenticatedSignedWrites": false,
                "extendedProperties": false
            },
            "descriptors": [],
            "permissions": null
        },
        {
            "serviceUUID": "ff00",
            "UUID": "ff07",
            "name": "ff07",
                    "propertie
s": {
                        "read": true,
            "write": true,
            "writeWithoutResponse": false,
            "notify": false,
            "indicate": false,
            "broadcast": false,
            "authenticatedSignedWrites": false,
            "extendedProperties": false
        },
        "descriptors": [],
        "permissions": null
    },
    {
        "serviceUUID": "ff00",
        "UUID": "ff08",
        "name": "ff08",
        "properties": {
            "read": true,
            "write": true,
            "writeWithoutResponse": false,
            "notify": false,
            "indicate": false,
            "broadcast": false,
            "authenticatedSignedWrites": false,
            "extendedProperties": false
        },
        "descriptors": [],
        "permissions": null
    }
]
}
],
"localName": "iBKS105",
"manufacturerId": 76,
"advertismentData": {
"scanRecord": {}
}
}

**Comment by farfromrefug** [comment]
@ju4nj3 you have to read it yourself. See https://stackoverflow.com/questions/18906988/what-is-the-ibeacon-bluetooth-profile

**Comment by ju4nj3** [comment]
@farfromrefug Hi, thanks for the documentation. I readed a lot about beacons before I posted this, but my question is simple: 
How can I discover beacons by UUID/minor/major instead of service using this plugin? Anyone?

**Comment by farfromrefug** [comment]
@ju4nj3 you need to look at native docs. This plugin is just a wrapper around native APIs

**Comment by ju4nj3** [comment]
Thank you very much @farfromrefug 
Finally I found a simple solution using this plugin [https://github.com/demetrio812/nativescript-ibeacon] which still works.

**Comment by farfromrefug** [comment]
@ju4nj3 seeing the code it makes sense to be in a different plugin. It is very specific code. Thanks for sharing!
