### ISSUE TITLE
startScanning doing nothing

### ISSUE THREAD

**Issue by erik777** [nativescript-community/ble#253]
I get nothing back via onDiscovered, nor the then or error result of startScanning...

```
          console.log("startScanning - calling");
          this.btInstance
              .startScanning({
                  seconds: 4,
                  onDiscovered: (perip: Peripheral) => {
                    console.log(`onDiscovered()`);
                  }
              })
              .then(() => {
	                console.log(`startScanning - then`);
	            	  this.isLoading = false;
	              },
                (err: any) => {
                  console.log(`startScanning - err`);
                }
              );
          console.log("startScanning - called");
```

Note that I do get a then called for btInstance.enable() with true when on mobile, false when on the emulator.  The then on btInstance.stopScanning() is also successfully called.  I receive a console.log for that.  I have to hit a button to invoke stopScanning, so it is not interferring.  Even if it did, one would expect the then on the startScanning to be called, but even stopScanning doesn't cause it to be invoked.  

But, for startScanning, the only logging I'm getting is before and after it is called.

```
  JS: startScanning - calling
  JS: startScanning - called
```

Nothing happens after 4 seconds, either.  I started with 50 seconds and reduced over time.  

Tried on two different phones, one with Android 11, another with Android 12L.  Both do the same.  

There are plenty of BT devices nearby.  I'm replacing a Cordova app that works fine on both phones and begins by discovering devices nearby.  

The first time i press the button to startScanning after installing the app, it prompts for location access, which I allow.  

I was originally using 

```
this.btInstance.on(Bluetooth.device_discovered_event, (eventData: any) => {
```

that didn't work either.  That's when I switched to using onDiscovered.  

Here is my package.json:

```
{
  "name": "osBT-ts",
  "main": "app/app.ts",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "@nativescript-community/ble": "^3.1.10",
    "@nativescript/core": "~8.3.0",
    "@nativescript/theme": "~3.0.2",
    "nativescript-vue": "~2.9.0"
  },
  "devDependencies": {
    "@nativescript/android": "8.3.1",
    "@nativescript/types": "~8.3.0",
    "@nativescript/webpack": "~5.0.9",
    "@types/node": "~17.0.21",
    "nativescript-vue-template-compiler": "~2.9.0",
    "typescript": "~4.5.5",
    "vue": "~2.6.12"
  }
}
```

**Comment by farfromrefug** [comment]
@erik777 did you request the correct permissions ? Android 11+ requires new permissions.

**Comment by erik777** [comment]
> @erik777 did you request the correct permissions ? Android 11+ requires new permissions.

I thought the prompt for location access was enough, which i grant.  Do I need to add code to explicitly request permissions?  This is in debug mode.  

Shouldn't the call to startScanning result in an error if permissions are not granted?  The promise is not rejected.

**Comment by farfromrefug** [comment]
The demo is quite old and android is moving really fast. It is best or you to look at android docs to understand things and what perms are needed. Then you can use @nativescript-community/perms to ask for the permission

**Comment by erik777** [comment]
Thanks for your help.  I installed and got perms working.  When I check perms, it says it is authorized for "bluetooth" and "bluetoothScan", and "undetermined" for location.  Then, `requestPermission(['location', 'bluetooth', 'bluetoothScan']` says "authorized" for course location, bluetooth scan and bluetooth advertise.  When I drill into App settings permissions, it has the same permissions as my working Cordova app, including "Location" and "Nearby Devices".  It's looking less like an issue with perms.

**Comment by farfromrefug** [comment]
@erik777 did not know about the neverForLocation breaking scanning. Always use both ;)
Thanks for explaining here might help others !

**Comment by erik777** [comment]
Yeah, scanning is working now.  Thanks for your help!  I'll worry about fine-tuning it later (perhaps with filters) to try to reduce permission requirements.  

A little off-topic, so if you want me to create another issue to ask, I can...  

The ultimate goal is to provide a P2P service with devices automatically discovering each other.  I'm a bit new to bluetooth, but doesn't that mean I'll need the ADVERTISE ability?  I don't see it exposed in the ble library.  Or, is there another way to accomplish this?  

If it is not in ns-ble, I'm opening to learning how to expose it and creating a PR, though that could take some time.

**Comment by farfromrefug** [comment]
@erik777 can we close this?

**Comment by erik777** [comment]
Yeah.  I have a new issue with services, but I'll open a new ticket for it.
