### ISSUE TITLE
Android - Characteristics Read, Write and Discover not working

### ISSUE THREAD

**Issue by matteonatale** [nativescript-community/ble#260]
Hi there,
I'm working on an app that needs to communicate with BLE devices. After some reports from users I've tested it out and I've seen that Read operations are not working (only) on Android 13. This is the error I get.

`[BluetoothError]:error_function_call, readCharacteristic, [B@8ec8a72, {"peripheralUUID":"78:E3:6D:11:3E:92","serviceUUID":"95f55846-471c-4a08-976c-e0f2c4c17da3","characteristicUUID":"8081050d-fbcc-46c1-bc2b-9db07ca0877e"}`

I've noticed that I was using an old plugin version (`3.0.31`) so I've updated the plugin to the latest version (`3.1.11`) and nothing changed as regards Read operation, it just doesn't work either. But for what concerns write operation, after the update, I've seen that those are not working correctly (but not only for Android 13). In fact after the first write operation is performed without any problem, all the other attempts throw this error.

`Error: java.nio.BufferUnderflowException writeValueToChar`

I've also done some more testing and I've discovered that also characteristic discovering is not working (but I've tested it on Android 13 only). The following error is thrown.

`TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them`

Actually discovering characteristic is not an operation that the app needs to perform, it was just for testing purposes.

Is there anything I can do to solve those issues?

Thanks for your help,
Matteo.

**Comment by prabudevarrajan1** [comment]
similar issue. Please help

```
 BluetoothService: Read error: [BluetoothError]:error_function_call, readCharacteristic, [B@260bdf5, {"peripheralUUID":"XX:B4:6A:C9:75:AB","serviceUUID":"fe78","characteristicUUID":"73fdxxx-626c-4f9b-a52e-b1d226efcf8d"}
```
