### ISSUE TITLE
sdk 33 , permission BLUETOOTH_SCAN  on startScanning

### ISSUE THREAD

**Issue by eblomyac** [nativescript-community/ble#269]
Hello,

@nativescript-community/ble": "3.1.15" also trying with 3.0.33
@nativescript/core": "~8.2.0"

On Android, SDK 33 i have an issue on startScanning:
SecurityException: Need android permission BLUETOOTH_SCAN , 
but i'm already added this permission to manifest file

**Comment by farfromrefug** [comment]
@eblomyac you need to ask the user at runtime (you can use @nativescript-community/perms).
I always advice to read android /iOS documentation for bluetooth.
