### ISSUE TITLE
Adroid 6 - check if location service is enabled

### ISSUE THREAD

**Issue by mprokopowicz** [nativescript-community/ble#5]
On Android 6, user have to enable location service (Settings -> Location -> On) to make this plugin (And all BLE depended apps) working.

If we have `hasCoarseLocationPermission` and `requestCoarseLocationPermission` methods, then, there should be also similar methods for location service.

Or at least it will be good to make a note about this in readme :)

**Comment by EddyVerbruggen** [comment]
Oh, intersting, thanks for letting me know.

So we can indeed check at runtime if it's enabled and add an option for the developer to prompt the user to go to the settings app to toggle it. [Details on SO.](http://stackoverflow.com/questions/33043582/bluetooth-low-energy-startscan-on-android-6-0-does-not-find-devices/33045489#33045489)
