### ISSUE TITLE
Estimote Beacons, iBeacons

### ISSUE THREAD

**Issue by RSwanson3** [nativescript-community/ble#58]
I am attempting to use this module to detect Estimote beacons. The main issue I'm having is with the optional params of the StartScanning function.

bluetooth.startScanning({
  serviceUUIDs: [],
  seconds: 4,
  onDiscovered: function (peripheral) {
  	console.log("Periperhal found with UUID: " + peripheral.UUID);
  }
})

Estimote beacons don't have a serviceUUID, at least none that I could find after looking around. So, I'm not sure how to go about filtering the beacons from the other bluetooth devices being detected by the scanner and I'm not sure how to go about identifying individual beacons. 

Thanks.

**Comment by allnash** [comment]
Yeah I don't think AdvData is exposed. More can be done if the key value is passed so we can do anything we want.
