### ISSUE TITLE
serviceUUID and characteristicUUIDunknown

### ISSUE THREAD

**Issue by peppeg85** [nativescript-community/ble#61]
hello, 

i have got a HM-10 BLE device, when i connect i have no services in the peripheral properties, i just need to send a character like "a" or "b", how can I make it works?
this is the scancallback result:

Lollipop+ scanCallback result: {"type":"scanResult","UUID":"50:8C:B1:6A:7C:AB","name":"HMSoft","RSSI":-71,"
state":"disconnected","advertisement":"AgEGCf9ITVCMsWp8qwcWALAAAAAAAwLg/wIKAAcJSE1Tb2Z0AAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAA=","manufacturerId":19784,"manufacturerData":{}}

i have found on this site these services: 
http://blog.blecentral.com/2015/05/05/hm-10-peripheral/
Service UUID: 0000ffe0-0000-1000-8000-00805f9b34fb) that enables bidirectional communication between the module and any other central device that connects to it. The service defines a single characteristic (Characteristic UUID: 0000ffe1-0000-1000-8000-00805f9b34fb) 
so if I try to connect and write the ascii for "a" I have this result:
Connecting to peripheral with UUID: 50:8C:B1:6A:7C:AB
JS: ------- _MyGattCallback.onConnectionStateChange, status: 0, new state: 2
JS: ---- discovering services..
JS: ------- _MyGattCallback.onConnectionStateChange, status: 8, new state: 0
JS: ----- invoking disc cb
JS: Periperhal disconnected with UUID: 50:8C:B1:6A:7C:AB

someone have ever worked with this device? where am i wrong?

thank you

**Comment by AleeeKoi** [comment]
Hi @peppeg85 ,
Did you find a solution? I have a similar problem.
