### ISSUE TITLE
writeWithoutResponse() returns too quickly on Android

### ISSUE THREAD

**Issue by kanayo** [nativescript-community/ble#62]
I used your Cordova plugin to talk to a AnD BLE scale  with success.

Now porting the app over to NativeScript and using this plugin.

Ran into a problem on Android using writeWithoutResponse(). The old plugin waited for onCharacteristicWrite() to be called before calling the success callback. This plugin returns immediately.  

Now when starting another BLE call after writeWithoutResponse() returns it fails. 

I changed writeWithoutResponse() to use the same logic as write(), setting the onWritePromise, and it all works perfectly.

**Comment by EddyVerbruggen** [comment]
Are you willing to share your patch by means of a PR perhaps?

**Comment by kanayo** [comment]
Yes, just working on that now.

**Comment by EddyVerbruggen** [comment]
That's awesome, take your time, and thanks in advance!
