### ISSUE TITLE
Bluetooth connection remains active even after calling disconnect on android

### ISSUE THREAD

**Issue by finger563** [nativescript-community/ble#68]
Happens after calling `startNotify()` on characteristics.

even after calling `stopNotify()` on all subscribed characteristics (and waiting for their promises to be resolved) and *then* calling `disconnect()`, the connection remains active.  can only be terminated by going into the settings of the phone and turning off Bluetooth.  connection even persists through app restarts (e.g. `tns run android` refreshing the app)

**Comment by antfarm** [comment]
Any ideas?

**Comment by finger563** [comment]
I think it's actually a device driver implementation issue, since it's not consistent across the devices I have.  I have actually gotten to where I just call `disable`, wait, then call `enable` on the Bluetooth chip which works across *most* devices - even still some retain connections.
