### ISSUE TITLE
onNotify result

### ISSUE THREAD

**Issue by peppeg85** [nativescript-community/ble#75]
hello, here i am again, i'm trying to read data sent by arduino inside the console with an hm-10 ble module, when i send something in the console i have this result:  ------- _MyGattCallback.onCharacteristicChanged
 but i can not read the characters that i've sent, where am i wrong? i've tryed with and without json stringify in the console log but nothing has changed, i've put the startNotifying inside the onConnected, is it wrong?

here is part of code:

bluetooth.connect({
            UUID: id,
            onConnected: function (peripheral) {
            device.push({
                'peripheralUUID': selectedUUID,
                'serviceUUID': '0000ffe0-0000-1000-8000-00805f9b34fb',
                'characteristicUUID': '0000ffe1-0000-1000-8000-00805f9b34fb',
                'name': selectedName,
                'seriale':serial
            });
            peripheralUUID=device[0].peripheralUUID;
            serviceUUID=device[0].serviceUUID;
            characteristicUUID=device[0].characteristicUUID;

            bluetooth.startNotifying({
                peripheralUUID: peripheralUUID,
                serviceUUID: serviceUUID,
                characteristicUUID: characteristicUUID,
                onNotify: function (result) {
                    console.log("read: ", result);
                }
            }).then(function() {
                console.log("subscribed for notifications");
            })
        },
        onDisconnected: function (peripheral) {
            console.log("Periperhal disconnected with UUID: " + selectedUUID);
        }
    });

thank you in advance

update: moreover, if i try to disconnect now it doesn't, maybe it stucks in some "notifying state"?
i've tryed with an ble app from the palay store and i can read the notifying value

**Comment by peppeg85** [comment]
sorry, i've called the function by pressing a button and the notifying works, but now i'm not able to console.log the datas since nativescript log system is tricky

**Comment by peppeg85** [comment]
sorry again, is bluetooth.connect a promise? if i call the startnotify with a then after the bluetooth.connect it isnt called, if i do manually with a button it works, how can i fix this?

**Comment by EddyVerbruggen** [comment]
It's a bit confusing to me that this issue is actually multiple issues in 1, but I'd like to respond to your last question: yes it's a promise, but it seemed to never resolve on Android. That will be fixed in the next version (>1.3.0).

**Comment by peppeg85** [comment]
It should wait for an ack by The bt , in this moment i fixed with a timeout
of 2seconds, but its not stable

Il mar 27 mar 2018, 20:33 Eddy Verbruggen <notifications@github.com> ha
scritto:

**Comment by EddyVerbruggen** [comment]
That's what the `onDiscovered` callback function is for, don't use the promise for that.

**Comment by peppeg85** [comment]
Ok, so the ack is not the solution. Maybe i don't use the on notify
properly?
Il mar 27 mar 2018, 20:45 Eddy Verbruggen <notifications@github.com> ha
scritto:
