### ISSUE TITLE
Incorrect Characteristics being read ?

### ISSUE THREAD

**Issue by georgeedwards** [nativescript-community/ble#9]
I have a Bluetooth module which is broadcasting a custom BLE service. I have been using the LightBlue iOS app to debug. This is showing the results I expect:
[![enter image description here](http://i.stack.imgur.com/9g8ZW.png)](http://i.stack.imgur.com/9g8ZW.png)
However, when using your plugin and then your demo app, I have found it is showing a different service on the exact same service, on the same device. Why is this?

See below:
[![enter image description here](http://i.stack.imgur.com/EYkcO.png)](http://i.stack.imgur.com/EYkcO.png)

**Comment by EddyVerbruggen** [comment]
Don't you see the correct properties when pressing the A000 service?

**Comment by georgeedwards** [comment]
Yes, it's the A004 Vs. 180D service that seems to have been picked up incorrectly?

**Comment by EddyVerbruggen** [comment]
I mean: if you press the `A000` service doesn't the screen slide to the next page where the characteristics are shown? Please attach a screenshot of that page as well.
