### ISSUE TITLE
manufacturerData always empty

### ISSUE THREAD

**Issue by msn444** [nativescript-community/ble#96]
Upon scanning a peripheral with manufacturer-specific data in the advertising packet, onDiscovered only returns the manufacturerId property (correctly populated with the first 2 bytes of the manufacturer-specific data) but the manufacturerData property is always empty.

Does the manufacturer-specific data from the peripheral need to be structured in some way to be parsed and returned as manufacturerData?

FYI: I am using iOS and I haven't tried it on Android.

**Comment by dbenninger** [comment]
I am using the manufacturerId and manufacturerData in our project and it works fine on both iOS and Android. Afaik, the manufacturer specific data does not have to be structured in a certain way. 

Have you checked with a BLE tester app (e.g. nRF Connect, https://itunes.apple.com/us/app/nrf-connect/id1054362403?mt=8) whether the manufacturer data is actually in the advertising?
