### ISSUE TITLE
iOS isBluetoothEnabled always return false

### ISSUE THREAD

**Issue by henrywongkar** [nativescript-community/ble#98]
bluetooth.isBluetoothEnabled().then(
    function(enabled) {
        console.log("Enabled? " + enabled);
);

isBluetoothEnabled is always returning false eventhough I have turned on my ipad mini bluetooth.
My ipad mini is using 9.3.5 which the latest version for ipad mini.
I built ios app using nativescript sidekick in a linux laptop.
I don't have problem running this in my android tab, iphone, and ipad running iOS 11. Works really fine.
I hope below information can help. Thanks a lot.

"nativescript": {
    "id": "com.xxx.xxx",
    "tns-ios": {
      "version": "4.2.0"
    },
    "tns-android": {
      "version": "4.2.0"
    }
  },
  "dependencies": {
    "@angular/common": "^6.1.0",
    "@angular/compiler": "^6.1.0",
    "@angular/core": "^6.1.0",
    "@angular/forms": "^6.1.0",
    "@angular/http": "^6.1.0",
    "@angular/platform-browser": "^6.1.0",
    "@angular/platform-browser-dynamic": "^6.1.0",
    "@angular/router": "^6.1.0",
    "kinvey-nativescript-sdk": "^3.11.5",
    "nativescript-angular": "next",
    "nativescript-bluetooth": "^1.3.1",
    "nativescript-camera": "~3.1.2",
    "nativescript-geolocation": "^4.3.0",
    "nativescript-intl": "~3.0.0",
    "nativescript-theme-core": "^1.0.4",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~6.0.0",
    "tns-core-modules": "next",
    "zone.js": "^0.8.26"
  },
"devDependencies": {
    "@angular-devkit/build-angular": "^0.7.1",
    "@angular-devkit/core": "^0.5.13",
    "@angular/compiler-cli": "^6.1.0",
    "@ngtools/webpack": "^6.1.1",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.10.0",
    "clean-webpack-plugin": "~0.1.19",
    "codelyzer": "^3.0.1",
    "copy-webpack-plugin": "^4.5.2",
    "css-loader": "^0.28.11",
    "extract-text-webpack-plugin": "~3.0.2",
    "fs-extra": "^0.30.0",
    "glob": "^7.1.2",
    "lazy": "1.0.11",
    "markdown-snippet-injector": "^0.2.0",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-typescript": "next",
    "nativescript-dev-webpack": "next",
    "nativescript-worker-loader": "~0.8.1",
    "opener": "^1.4.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.3.0",
    "rimraf": "^2.5.3",
    "tar.gz": "^1.0.5",
    "tns-platform-declarations": "^3.4.1",
    "tslint": "^5.11.0",
    "typescript": "~2.7.2",
    "uglifyjs-webpack-plugin": "^1.2.7",
    "webpack": "~4.5.0",
    "webpack-bundle-analyzer": "^2.13.1",
    "webpack-cli": "~2.0.14",
    "webpack-sources": "~1.1.0"
  },

**Comment by ish2028** [comment]
`isBluetoothEnabled` should be false initially until the delegate method `centralManagerDidUpdateState` is called and the state is `poweredOn`.  For iOS there should be a callback implemented for then this happens so that we know when to start scanning.
